image:
  - Visual Studio 2019
  - Ubuntu

skip_branch_with_pr: true
skip_commits:
  files:
    - '**/*.md'

environment:
  JERRY_SQLSERVER_CONN: SERVER=localhost;DATABASE=jerry_testdb;USER ID=sa;PASSWORD=Password12!
  JERRY_POSTGRES_CONN: SERVER=localhost;PORT=5432;DATABASE=jerry_testdb;USER ID=postgres;PASSWORD=Password12!
  JERRY_MYSQL_CONN: SERVER=localhost;DATABASE=jerry_testdb;UID=root;PWD=Password12!;

services:
  - mssql2017
  - postgresql
  - mysql

init:
  - cmd: SET PATH=%PATH%;C:\Program Files\PostgreSQL\9.6\bin\;C:\Program Files\MySQL\MySQL Server 5.7\bin\
  - cmd: SET PGUSER=postgres
  - cmd: SET PGPASSWORD=Password12!

build_script:
  - dotnet --info
  - createdb jerry_testdb
  - sh: psql -c "ALTER USER appveyor WITH PASSWORD 'Password12!'" -d jerry_testdb
  - sh: sleep 20s
  - sqlcmd -S "(local)" -U "sa" -P "Password12!" -Q "CREATE DATABASE jerry_testdb;"
  - mysql -e "create database jerry_testdb;" --user=root --password=Password12!
  - ps: .\build.ps1

test: off

for:
-
  branches:
    only:
      - master
      - dev

  artifacts:
  - path: .\artifacts\packages\*.nupkg
  - path: .\artifacts\packages\*.snupkg